### Reproducible results using seed

In [1]:
import tensorflow as tf
import numpy as np
import random as rn

In [2]:
# the Keras documentation lets us know that the piece of code below is necessary for any reproducibility for
# certain hash based algorithms, so we put this in directly underneath our import statements.
import os
os.environ['PYTHONHASHSEED'] = '0'

In [3]:
# numpy random seed
np.random.seed(37)

In [4]:
# python random seed
rn.seed(1254)

In [5]:
# tensorflow random seed
tf.random.set_seed(89)

In [6]:
### Bias
from keras.models import Sequential
from keras.layers import Dense

In [9]:
model = Sequential([
            Dense(4, input_shape=(1,), activation='relu', use_bias=True, bias_initializer='zeros'),
            Dense(2, activation='softmax')
])

In [11]:
model.get_weights()

[array([[-0.5333039, -0.8589198,  0.0159899, -0.6266952]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.56253076,  0.3659532 ],
        [ 0.673604  , -0.47082686],
        [-0.6892462 ,  0.19190264],
        [ 0.8937402 ,  0.9475126 ]], dtype=float32),
 array([0., 0.], dtype=float32)]

### Learnable parameters

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 4)                 8         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 10        
Total params: 18
Trainable params: 18
Non-trainable params: 0
_________________________________________________________________


In [13]:
# Param is the num of learnable parameters
# this can also be inferred from below 
model.get_weights()

[array([[-0.5333039, -0.8589198,  0.0159899, -0.6266952]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.56253076,  0.3659532 ],
        [ 0.673604  , -0.47082686],
        [-0.6892462 ,  0.19190264],
        [ 0.8937402 ,  0.9475126 ]], dtype=float32),
 array([0., 0.], dtype=float32)]